name: container action
  

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    container: unityofdisaster/node-with-angular
    steps: 
      - name: check node version
        run: node -v
      - name: check angular cli version
        run: ng --version
